const words = {
  people: [
    {
      word: 'person',
      translation: 'человек',
      image: 'assets/images/person/person.jpg',
      audioSrc: 'assets/music/person/person.mp3',
    },
    {
      word: 'man',
      translation: 'мужчина',
      image: 'assets/images/person/man.jpg',
      audioSrc: 'assets/music/person/man.mp3',
    },
    {
      word: 'woman',
      translation: 'женщина',
      image: 'assets/images/person/woman.jpg',
      audioSrc: 'assets/music/person/woman.mp3',
    },
    {
      word: 'child',
      translation: 'ребенок',
      image: 'assets/images/person/child.jpg',
      audioSrc: 'assets/music/person/child.mp3',
    },
    {
      word: 'boy',
      translation: 'мальчик',
      image: 'assets/images/person/boy.jpg',
      audioSrc: 'assets/music/person/boy.mp3',
    },
    {
      word: 'girl',
      translation: 'девочка',
      image: 'assets/images/person/girl.jpg',
      audioSrc: 'assets/music/person/girl.mp3',
    },
    {
      word: 'friend',
      translation: 'друг',
      image: 'assets/images/person/friend.jpg',
      audioSrc: 'assets/music/person/friend.mp3',
    },
    {
      word: 'neighbor',
      translation: 'сосед',
      image: 'assets/images/person/neighbor.jpg',
      audioSrc: 'assets/music/person/neighbor.mp3',
    },
    {
      word: 'name',
      translation: 'имя, название',
      image: 'assets/images/person/name.jpg',
      audioSrc: 'assets/music/person/name.mp3',
    },
    {
      word: 'surname',
      translation: 'фамилия',
      image: 'assets/images/person/surname.jpg',
      audioSrc: 'assets/music/person/surname.mp3',
    },
    {
      word: 'address',
      translation: 'адрес',
      image: 'assets/images/person/address.jpg',
      audioSrc: 'assets/music/person/address.mp3',
    },
    {
      word: 'single',
      translation: 'холостой/незамужняя',
      image: 'assets/images/person/single.jpg',
      audioSrc: 'assets/music/person/single.mp3',
    },
    {
      word: 'married',
      translation: 'женатый/замужняя',
      image: 'assets/images/person/married.jpg',
      audioSrc: 'assets/music/person/married.mp3',
    },
    {
      word: 'age',
      translation: 'возраст',
      image: 'assets/images/person/age.jpg',
      audioSrc: 'assets/music/person/age.mp3',
    },
    {
      word: 'old',
      translation: 'старый',
      image: 'assets/images/person/old.jpg',
      audioSrc: 'assets/music/person/old.mp3',
    },
    {
      word: 'young',
      translation: 'молодой',
      image: 'assets/images/person/young.jpg',
      audioSrc: 'assets/music/person/young.mp3',
    },
    {
      word: 'I',
      translation: 'я',
      image: 'assets/images/person/i.jpg',
      audioSrc: 'assets/music/person/i.mp3',
    },
    {
      word: 'you',
      translation: 'ты, вы',
      image: 'assets/images/person/you.jpg',
      audioSrc: 'assets/music/person/you.mp3',
    },
    {
      word: 'we',
      translation: 'мы',
      image: 'assets/images/person/we.jpg',
      audioSrc: 'assets/music/person/we.mp3',
    },
    {
      word: 'they',
      translation: 'они',
      image: 'assets/images/person/they.jpg',
      audioSrc: 'assets/music/person/they.mp3',
    },
    {
      word: 'he',
      translation: 'он',
      image: 'assets/images/person/he.jpg',
      audioSrc: 'assets/music/person/he.mp3',
    },
    {
      word: 'she',
      translation: 'она',
      image: 'assets/images/person/she.jpg',
      audioSrc: 'assets/music/person/she.mp3',
    },
    {
      word: 'it',
      translation: 'оно',
      image: 'assets/images/person/it.jpg',
      audioSrc: 'assets/music/person/it.mp3',
    },
    {
      word: 'parent',
      translation: 'родители',
      image: 'assets/images/person/parent.jpg',
      audioSrc: 'assets/music/person/parent.mp3',
    },
    {
      word: 'father',
      translation: 'отец',
      image: 'assets/images/person/father.jpg',
      audioSrc: 'assets/music/person/father.mp3',
    },
    {
      word: 'mother',
      translation: 'мать',
      image: 'assets/images/person/mother.jpg',
      audioSrc: 'assets/music/person/mother.mp3',
    },
    {
      word: 'son',
      translation: 'сын',
      image: 'assets/images/person/son.jpg',
      audioSrc: 'assets/music/person/son.mp3',
    },
    {
      word: 'daughter',
      translation: 'дочь',
      image: 'assets/images/person/daughter.jpg',
      audioSrc: 'assets/music/person/daughter.mp3',
    },
    {
      word: 'brother',
      translation: 'брат',
      image: 'assets/images/person/brother.jpg',
      audioSrc: 'assets/music/person/brother.mp3',
    },
    {
      word: 'sister',
      translation: 'сестра',
      image: 'assets/images/person/sister.jpg',
      audioSrc: 'assets/music/person/sister.mp3',
    },
    {
      word: 'grandfather',
      translation: 'дедушка',
      image: 'assets/images/person/grandfather.jpg',
      audioSrc: 'assets/music/person/grandfather.mp3',
    },
    {
      word: 'grandmother',
      translation: 'бабушка',
      image: 'assets/images/person/grandmother.jpg',
      audioSrc: 'assets/music/person/grandmother.mp3',
    },
    {
      word: 'uncle',
      translation: 'дядя',
      image: 'assets/images/person/uncle.jpg',
      audioSrc: 'assets/music/person/uncle.mp3',
    },
    {
      word: 'aunt',
      translation: 'тётя',
      image: 'assets/images/person/aunt.jpg',
      audioSrc: 'assets/music/person/aunt.mp3',
    },
    {
      word: 'cousin',
      translation: 'двоюродный брат/сестра',
      image: 'assets/images/person/cousin.jpg',
      audioSrc: 'assets/music/person/cousin.mp3',
    },
    {
      word: 'arm',
      translation: 'рука',
      image: 'assets/images/person/arm.jpg',
      audioSrc: 'assets/music/person/arm.mp3',
    },
    {
      word: 'back',
      translation: 'спина',
      image: 'assets/images/person/back.jpg',
      audioSrc: 'assets/music/person/back.mp3',
    },
    {
      word: 'beard',
      translation: 'борода',
      image: 'assets/images/person/beard.jpg',
      audioSrc: 'assets/music/person/beard.mp3',
    },
    {
      word: 'bone',
      translation: 'кость',
      image: 'assets/images/person/bone.jpg',
      audioSrc: 'assets/music/person/bone.mp3',
    },
    {
      word: 'buttocks',
      translation: 'ягодица',
      image: 'assets/images/person/buttocks.jpg',
      audioSrc: 'assets/music/person/buttocks.mp3',
    },
    {
      word: 'cheek',
      translation: 'щека',
      image: 'assets/images/person/cheek.jpg',
      audioSrc: 'assets/music/person/cheek.mp3',
    },
    {
      word: 'chest',
      translation: 'грудь',
      image: 'assets/images/person/chest.jpg',
      audioSrc: 'assets/music/person/chest.mp3',
    },
    {
      word: 'chin',
      translation: 'подбородок',
      image: 'assets/images/person/chin.jpg',
      audioSrc: 'assets/music/person/chin.mp3',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: 'assets/images/person/ear.jpg',
      audioSrc: 'assets/music/person/ear.mp3',
    },
    {
      word: 'elbow',
      translation: 'локоть',
      image: 'assets/images/person/elbow.jpg',
      audioSrc: 'assets/music/person/elbow.mp3',
    },
    {
      word: 'eye',
      translation: 'глаз',
      image: 'assets/images/person/eye.jpg',
      audioSrc: 'assets/music/person/eye.mp3',
    },
    {
      word: 'eyebrow',
      translation: 'бровь',
      image: 'assets/images/person/eyebrow.jpg',
      audioSrc: 'assets/music/person/eyebrow.mp3',
    },
    {
      word: 'face',
      translation: 'лицо',
      image: 'assets/images/person/face.jpg',
      audioSrc: 'assets/music/person/face.mp3',
    },
    {
      word: 'finger',
      translation: 'палец',
      image: 'assets/images/person/finger.jpg',
      audioSrc: 'assets/music/person/finger.mp3',
    },
    {
      word: 'foot',
      translation: 'ступня',
      image: 'assets/images/person/foot.jpg',
      audioSrc: 'assets/music/person/foot.mp3',
    },
    {
      word: 'forehead',
      translation: 'лоб',
      image: 'assets/images/person/forehead.jpg',
      audioSrc: 'assets/music/person/forehead.mp3',
    },
    {
      word: 'hair',
      translation: 'волосы',
      image: 'assets/images/person/hair.jpg',
      audioSrc: 'assets/music/person/hair.mp3',
    },
    {
      word: 'hand',
      translation: 'кисти рук',
      image: 'assets/images/person/hand.jpg',
      audioSrc: 'assets/music/person/hand.mp3',
    },
    {
      word: 'head',
      translation: 'голова',
      image: 'assets/images/person/head.jpg',
      audioSrc: 'assets/music/person/head.mp3',
    },
    {
      word: 'heart',
      translation: 'сердце',
      image: 'assets/images/person/heart.jpg',
      audioSrc: 'assets/music/person/heart.mp3',
    },
    {
      word: 'heel',
      translation: 'пятка',
      image: 'assets/images/person/heel.jpg',
      audioSrc: 'assets/music/person/heel.mp3',
    },
    {
      word: 'knee',
      translation: 'колено',
      image: 'assets/images/person/knee.jpg',
      audioSrc: 'assets/music/person/knee.mp3',
    },
    {
      word: 'leg',
      translation: 'нога',
      image: 'assets/images/person/leg.jpg',
      audioSrc: 'assets/music/person/leg.mp3',
    },
    {
      word: 'lips',
      translation: 'губы',
      image: 'assets/images/person/lips.jpg',
      audioSrc: 'assets/music/person/lips.mp3',
    },
    {
      word: 'mouth',
      translation: 'рот',
      image: 'assets/images/person/mouth.jpg',
      audioSrc: 'assets/music/person/mouth.mp3',
    },
    {
      word: 'mustache',
      translation: 'усы',
      image: 'assets/images/person/mustache.jpg',
      audioSrc: 'assets/music/person/mustache.mp3',
    },
    {
      word: 'nail',
      translation: 'ноготь',
      image: 'assets/images/person/nail.jpg',
      audioSrc: 'assets/music/person/nail.mp3',
    },
    {
      word: 'neck',
      translation: 'шея',
      image: 'assets/images/person/neck.jpg',
      audioSrc: 'assets/music/person/neck.mp3',
    },
    {
      word: 'nose',
      translation: 'нос',
      image: 'assets/images/person/nose.jpg',
      audioSrc: 'assets/music/person/nose.mp3',
    },
    {
      word: 'organ',
      translation: 'орган',
      image: 'assets/images/person/organ.jpg',
      audioSrc: 'assets/music/person/organ.mp3',
    },
    {
      word: 'shoulder',
      translation: 'плечо',
      image: 'assets/images/person/shoulder.jpg',
      audioSrc: 'assets/music/person/shoulder.mp3',
    },
    {
      word: 'skin',
      translation: 'кожа',
      image: 'assets/images/person/skin.jpg',
      audioSrc: 'assets/music/person/skin.mp3',
    },
    {
      word: 'spine',
      translation: 'позвоночник',
      image: 'assets/images/person/spine.jpg',
      audioSrc: 'assets/music/person/spine.mp3',
    },
    {
      word: 'stomach',
      translation: 'живот, желудок',
      image: 'assets/images/person/stomach.jpg',
      audioSrc: 'assets/music/person/stomach.mp3',
    },
    {
      word: 'throat',
      translation: 'горло',
      image: 'assets/images/person/throat.jpg',
      audioSrc: 'assets/music/person/throat.mp3',
    },
    {
      word: 'toe',
      translation: 'палец на ноге',
      image: 'assets/images/person/toe.jpg',
      audioSrc: 'assets/music/person/toe.mp3',
    },
    {
      word: 'tongue',
      translation: 'язык',
      image: 'assets/images/person/tongue.jpg',
      audioSrc: 'assets/music/person/tongue.mp3',
    },
    {
      word: 'teeth',
      translation: 'зуб',
      image: 'assets/images/person/teeth.jpg',
      audioSrc: 'assets/music/person/teeth.mp3',
    },
    {
      word: 'blood',
      translation: 'кровь',
      image: 'assets/images/person/blood.jpg',
      audioSrc: 'assets/music/person/blood.mp3',
    },
    {
      word: 'bruise',
      translation: 'синяк',
      image: 'assets/images/person/bruise.jpg',
      audioSrc: 'assets/music/person/bruise.mp3',
    },
    {
      word: 'cough',
      translation: 'кашель',
      image: 'assets/images/person/cough.jpg',
      audioSrc: 'assets/music/person/cough.mp3',
    },
    {
      word: 'dizziness',
      translation: 'головокружение',
      image: 'assets/images/person/dizziness.jpg',
      audioSrc: 'assets/music/person/dizziness.mp3',
    },
    {
      word: 'fever',
      translation: 'жар',
      image: 'assets/images/person/fever.jpg',
      audioSrc: 'assets/music/person/fever.mp3',
    },
    {
      word: 'flu',
      translation: 'грипп',
      image: 'assets/images/person/flu.jpg',
      audioSrc: 'assets/music/person/flu.mp3',
    },
    {
      word: 'pain',
      translation: 'боль',
      image: 'assets/images/person/pain.jpg',
      audioSrc: 'assets/music/person/pain.mp3',
    },
    {
      word: 'running nose',
      translation: 'насморк',
      image: 'assets/images/person/running nose.jpg',
      audioSrc: 'assets/music/person/running nose.mp3',
    },
    {
      word: 'spot',
      translation: 'пятно, точка',
      image: 'assets/images/person/spot.jpg',
      audioSrc: 'assets/music/person/spot.mp3',
    },
    {
      word: 'wound',
      translation: 'рана',
      image: 'assets/images/person/wound.jpg',
      audioSrc: 'assets/music/person/wound.mp3',
    },
    {
      word: 'sneeze',
      translation: 'чихать',
      image: 'assets/images/person/sneeze.jpg',
      audioSrc: 'assets/music/person/sneeze.mp3',
    },
    {
      word: 'hurt',
      translation: 'ранить, повреждать',
      image: 'assets/images/person/hurt.jpg',
      audioSrc: 'assets/music/person/hurt.mp3',
    },
    {
      word: 'fit',
      translation: 'в хорошей форме',
      image: 'assets/images/person/fit.jpg',
      audioSrc: 'assets/music/person/fit.mp3',
    },
    {
      word: 'healthy',
      translation: 'здоровый',
      image: 'assets/images/person/healthy.jpg',
      audioSrc: 'assets/music/person/healthy.mp3',
    },
    {
      word: 'swollen',
      translation: 'опухший',
      image: 'assets/images/person/swollen.jpg',
      audioSrc: 'assets/music/person/swollen.mp3',
    },
    {
      word: 'sick',
      translation: 'больной',
      image: 'assets/images/person/sick.jpg',
      audioSrc: 'assets/music/person/sick.mp3',
    },
    {
      word: 'fat',
      translation: 'толстый, жирный',
      image: 'assets/images/person/fat.jpg',
      audioSrc: 'assets/music/person/fat.mp3',
    },
    {
      word: 'dead',
      translation: 'мертвый',
      image: 'assets/images/person/dead.jpg',
      audioSrc: 'assets/music/person/dead.mp3',
    },
    {
      word: 'positive',
      translation: 'положительный',
      image: 'assets/images/person/positive.jpg',
      audioSrc: 'assets/music/person/positive.mp3',
    },
    {
      word: 'amazing',
      translation: 'удивительный',
      image: 'assets/images/person/amazing.jpg',
      audioSrc: 'assets/music/person/amazing.mp3',
    },
    {
      word: 'beautiful',
      translation: 'красивый',
      image: 'assets/images/person/beautiful.jpg',
      audioSrc: 'assets/music/person/beautiful.mp3',
    },
    {
      word: 'handsome',
      translation: 'красивый (о мужчине)',
      image: 'assets/images/person/handsome.jpg',
      audioSrc: 'assets/music/person/handsome.mp3',
    },
    {
      word: 'brave',
      translation: 'смелый',
      image: 'assets/images/person/brave.jpg',
      audioSrc: 'assets/music/person/brave.mp3',
    },
    {
      word: 'calm',
      translation: 'спокойный',
      image: 'assets/images/person/calm.jpg',
      audioSrc: 'assets/music/person/calm.mp3',
    },
    {
      word: 'careful',
      translation: 'осторожный',
      image: 'assets/images/person/careful.jpg',
      audioSrc: 'assets/music/person/careful.mp3',
    },
    {
      word: 'clever',
      translation: 'умный',
      image: 'assets/images/person/clever.jpg',
      audioSrc: 'assets/music/person/clever.mp3',
    },
    {
      word: 'curious',
      translation: 'любопытный',
      image: 'assets/images/person/curious.jpg',
      audioSrc: 'assets/music/person/curious.mp3',
    },
    {
      word: 'elegant',
      translation: 'элегантный',
      image: 'assets/images/person/elegant.jpg',
      audioSrc: 'assets/music/person/elegant.mp3',
    },
    {
      word: 'energetic',
      translation: 'энергичный',
      image: 'assets/images/person/energetic.jpg',
      audioSrc: 'assets/music/person/energetic.mp3',
    },
    {
      word: 'fair',
      translation: 'справедливый, честный',
      image: 'assets/images/person/fair.jpg',
      audioSrc: 'assets/music/person/fair.mp3',
    },
    {
      word: 'fine',
      translation: 'прекрасный, прекрасно',
      image: 'assets/images/person/fine.jpg',
      audioSrc: 'assets/music/person/fine.mp3',
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      image: 'assets/images/person/friendly.jpg',
      audioSrc: 'assets/music/person/friendly.mp3',
    },
    {
      word: 'good',
      translation: 'хороший, добрый',
      image: 'assets/images/person/good.jpg',
      audioSrc: 'assets/music/person/good.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'assets/images/person/happy.jpg',
      audioSrc: 'assets/music/person/happy.mp3',
    },
    {
      word: 'hard-working',
      translation: 'трудолюбивый',
      image: 'assets/images/person/hard-working.jpg',
      audioSrc: 'assets/music/person/hard-working.mp3',
    },
    {
      word: 'honest',
      translation: 'честный',
      image: 'assets/images/person/honest.jpg',
      audioSrc: 'assets/music/person/honest.mp3',
    },
    {
      word: 'kind',
      translation: 'добрый',
      image: 'assets/images/person/kind.jpg',
      audioSrc: 'assets/music/person/kind.mp3',
    },
    {
      word: 'lucky',
      translation: 'везучий, счастливый',
      image: 'assets/images/person/lucky.jpg',
      audioSrc: 'assets/music/person/lucky.mp3',
    },
    {
      word: 'nice',
      translation: 'милый, хороший, приятный',
      image: 'assets/images/person/nice.jpg',
      audioSrc: 'assets/music/person/nice.mp3',
    },
    {
      word: 'polite',
      translation: 'вежливый',
      image: 'assets/images/person/polite.jpg',
      audioSrc: 'assets/music/person/polite.mp3',
    },
    {
      word: 'talented',
      translation: 'талантливый',
      image: 'assets/images/person/talented.jpg',
      audioSrc: 'assets/music/person/talented.mp3',
    },
  ],
};

export default words;
