const words = {
  people: [
    {
      word: 'person',
      translation: 'человек',
      image: 'assets/images/person/person.jpg',
      audioSrc: 'assets/music/person/person.mp3',
    },
    {
      word: 'man',
      translation: 'мужчина',
      image: 'assets/images/person/man.jpg',
      audioSrc: 'assets/music/person/man.mp3',
    },
    {
      word: 'woman',
      translation: 'женщина',
      image: 'assets/images/person/woman.jpg',
      audioSrc: 'assets/music/person/woman.mp3',
    },
    {
      word: 'child',
      translation: 'ребенок',
      image: 'assets/images/person/child.jpg',
      audioSrc: 'assets/music/person/child.mp3',
    },
    {
      word: 'boy',
      translation: 'мальчик',
      image: 'assets/images/person/boy.jpg',
      audioSrc: 'assets/music/person/boy.mp3',
    },
    {
      word: 'girl',
      translation: 'девочка',
      image: 'assets/images/person/girl.jpg',
      audioSrc: 'assets/music/person/girl.mp3',
    },
    {
      word: 'friend',
      translation: 'друг',
      image: 'assets/images/person/friend.jpg',
      audioSrc: 'assets/music/person/friend.mp3',
    },
    {
      word: 'neighbor',
      translation: 'сосед',
      image: 'assets/images/person/neighbor.jpg',
      audioSrc: 'assets/music/person/neighbor.mp3',
    },
    {
      word: 'name',
      translation: 'имя, название',
      image: 'assets/images/person/name.jpg',
      audioSrc: 'assets/music/person/name.mp3',
    },
    {
      word: 'surname',
      translation: 'фамилия',
      image: 'assets/images/person/surname.jpg',
      audioSrc: 'assets/music/person/surname.mp3',
    },
    {
      word: 'address',
      translation: 'адрес',
      image: 'assets/images/person/address.jpg',
      audioSrc: 'assets/music/person/address.mp3',
    },
    {
      word: 'single',
      translation: 'холостой/незамужняя',
      image: 'assets/images/person/single.jpg',
      audioSrc: 'assets/music/person/single.mp3',
    },
    {
      word: 'married',
      translation: 'женатый/замужняя',
      image: 'assets/images/person/married.jpg',
      audioSrc: 'assets/music/person/married.mp3',
    },
    {
      word: 'age',
      translation: 'возраст',
      image: 'assets/images/person/age.jpg',
      audioSrc: 'assets/music/person/age.mp3',
    },
    {
      word: 'old',
      translation: 'старый',
      image: 'assets/images/person/old.jpg',
      audioSrc: 'assets/music/person/old.mp3',
    },
    {
      word: 'young',
      translation: 'молодой',
      image: 'assets/images/person/young.jpg',
      audioSrc: 'assets/music/person/young.mp3',
    },
    {
      word: 'I',
      translation: 'я',
      image: 'assets/images/person/i.jpg',
      audioSrc: 'assets/music/person/i.mp3',
    },
    {
      word: 'you',
      translation: 'ты, вы',
      image: 'assets/images/person/you.jpg',
      audioSrc: 'assets/music/person/you.mp3',
    },
    {
      word: 'we',
      translation: 'мы',
      image: 'assets/images/person/we.jpg',
      audioSrc: 'assets/music/person/we.mp3',
    },
    {
      word: 'they',
      translation: 'они',
      image: 'assets/images/person/they.jpg',
      audioSrc: 'assets/music/person/they.mp3',
    },
    {
      word: 'he',
      translation: 'он',
      image: 'assets/images/person/he.jpg',
      audioSrc: 'assets/music/person/he.mp3',
    },
    {
      word: 'she',
      translation: 'она',
      image: 'assets/images/person/she.jpg',
      audioSrc: 'assets/music/person/she.mp3',
    },
    {
      word: 'it',
      translation: 'оно',
      image: 'assets/images/person/it.jpg',
      audioSrc: 'assets/music/person/it.mp3',
    },
    {
      word: 'parent',
      translation: 'родители',
      image: 'assets/images/person/parent.jpg',
      audioSrc: 'assets/music/person/parent.mp3',
    },
    {
      word: 'father',
      translation: 'отец',
      image: 'assets/images/person/father.jpg',
      audioSrc: 'assets/music/person/father.mp3',
    },
    {
      word: 'mother',
      translation: 'мать',
      image: 'assets/images/person/mother.jpg',
      audioSrc: 'assets/music/person/mother.mp3',
    },
    {
      word: 'son',
      translation: 'сын',
      image: 'assets/images/person/son.jpg',
      audioSrc: 'assets/music/person/son.mp3',
    },
    {
      word: 'daughter',
      translation: 'дочь',
      image: 'assets/images/person/daughter.jpg',
      audioSrc: 'assets/music/person/daughter.mp3',
    },
    {
      word: 'brother',
      translation: 'брат',
      image: 'assets/images/person/brother.jpg',
      audioSrc: 'assets/music/person/brother.mp3',
    },
    {
      word: 'sister',
      translation: 'сестра',
      image: 'assets/images/person/sister.jpg',
      audioSrc: 'assets/music/person/sister.mp3',
    },
    {
      word: 'grandfather',
      translation: 'дедушка',
      image: 'assets/images/person/grandfather.jpg',
      audioSrc: 'assets/music/person/grandfather.mp3',
    },
    {
      word: 'grandmother',
      translation: 'бабушка',
      image: 'assets/images/person/grandmother.jpg',
      audioSrc: 'assets/music/person/grandmother.mp3',
    },
    {
      word: 'uncle',
      translation: 'дядя',
      image: 'assets/images/person/uncle.jpg',
      audioSrc: 'assets/music/person/uncle.mp3',
    },
    {
      word: 'aunt',
      translation: 'тётя',
      image: 'assets/images/person/aunt.jpg',
      audioSrc: 'assets/music/person/aunt.mp3',
    },
    {
      word: 'cousin',
      translation: 'двоюродный брат/сестра',
      image: 'assets/images/person/cousin.jpg',
      audioSrc: 'assets/music/person/cousin.mp3',
    },
    {
      word: 'arm',
      translation: 'рука',
      image: 'assets/images/person/arm.jpg',
      audioSrc: 'assets/music/person/arm.mp3',
    },
    {
      word: 'back',
      translation: 'спина',
      image: 'assets/images/person/back.jpg',
      audioSrc: 'assets/music/person/back.mp3',
    },
    {
      word: 'beard',
      translation: 'борода',
      image: 'assets/images/person/beard.jpg',
      audioSrc: 'assets/music/person/beard.mp3',
    },
    {
      word: 'bone',
      translation: 'кость',
      image: 'assets/images/person/bone.jpg',
      audioSrc: 'assets/music/person/bone.mp3',
    },
    {
      word: 'buttocks',
      translation: 'ягодица',
      image: 'assets/images/person/buttocks.jpg',
      audioSrc: 'assets/music/person/buttocks.mp3',
    },
    {
      word: 'cheek',
      translation: 'щека',
      image: 'assets/images/person/cheek.jpg',
      audioSrc: 'assets/music/person/cheek.mp3',
    },
    {
      word: 'chest',
      translation: 'грудь',
      image: 'assets/images/person/chest.jpg',
      audioSrc: 'assets/music/person/chest.mp3',
    },
    {
      word: 'chin',
      translation: 'подбородок',
      image: 'assets/images/person/chin.jpg',
      audioSrc: 'assets/music/person/chin.mp3',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: 'assets/images/person/ear.jpg',
      audioSrc: 'assets/music/person/ear.mp3',
    },
  ],
};

export default words;
