const words = {
  people: [
    {
      word: 'person',
      translation: 'человек',
      image: 'assets/images/person/person.jpg',
      audioSrc: 'assets/music/person/person.mp3',
    },
    {
      word: 'man',
      translation: 'мужчина',
      image: 'assets/images/person/man.jpg',
      audioSrc: 'assets/music/person/man.mp3',
    },
    {
      word: 'woman',
      translation: 'женщина',
      image: 'assets/images/person/woman.jpg',
      audioSrc: 'assets/music/person/woman.mp3',
    },
    {
      word: 'child',
      translation: 'ребенок',
      image: 'assets/images/person/child.jpg',
      audioSrc: 'assets/music/person/child.mp3',
    },
    {
      word: 'boy',
      translation: 'мальчик',
      image: 'assets/images/person/boy.jpg',
      audioSrc: 'assets/music/person/boy.mp3',
    },
    {
      word: 'girl',
      translation: 'девочка',
      image: 'assets/images/person/girl.jpg',
      audioSrc: 'assets/music/person/girl.mp3',
    },
    {
      word: 'friend',
      translation: 'друг',
      image: 'assets/images/person/friend.jpg',
      audioSrc: 'assets/music/person/friend.mp3',
    },
    {
      word: 'neighbor',
      translation: 'сосед',
      image: 'assets/images/person/neighbor.jpg',
      audioSrc: 'assets/music/person/neighbor.mp3',
    },
    {
      word: 'name',
      translation: 'имя, название',
      image: 'assets/images/person/name.jpg',
      audioSrc: 'assets/music/person/name.mp3',
    },
    {
      word: 'surname',
      translation: 'фамилия',
      image: 'assets/images/person/surname.jpg',
      audioSrc: 'assets/music/person/surname.mp3',
    },
    {
      word: 'address',
      translation: 'адрес',
      image: 'assets/images/person/address.jpg',
      audioSrc: 'assets/music/person/address.mp3',
    },
    {
      word: 'single',
      translation: 'холостой/незамужняя',
      image: 'assets/images/person/single.jpg',
      audioSrc: 'assets/music/person/single.mp3',
    },
    {
      word: 'married',
      translation: 'женатый/замужняя',
      image: 'assets/images/person/married.jpg',
      audioSrc: 'assets/music/person/married.mp3',
    },
    {
      word: 'age',
      translation: 'возраст',
      image: 'assets/images/person/age.jpg',
      audioSrc: 'assets/music/person/age.mp3',
    },
    {
      word: 'old',
      translation: 'старый',
      image: 'assets/images/person/old.jpg',
      audioSrc: 'assets/music/person/old.mp3',
    },
    {
      word: 'young',
      translation: 'молодой',
      image: 'assets/images/person/young.jpg',
      audioSrc: 'assets/music/person/young.mp3',
    },
    {
      word: 'I',
      translation: 'я',
      image: 'assets/images/person/i.jpg',
      audioSrc: 'assets/music/person/i.mp3',
    },
    {
      word: 'you',
      translation: 'ты, вы',
      image: 'assets/images/person/you.jpg',
      audioSrc: 'assets/music/person/you.mp3',
    },
    {
      word: 'we',
      translation: 'мы',
      image: 'assets/images/person/we.jpg',
      audioSrc: 'assets/music/person/we.mp3',
    },
    {
      word: 'they',
      translation: 'они',
      image: 'assets/images/person/they.jpg',
      audioSrc: 'assets/music/person/they.mp3',
    },
    {
      word: 'he',
      translation: 'он',
      image: 'assets/images/person/he.jpg',
      audioSrc: 'assets/music/person/he.mp3',
    },
    {
      word: 'she',
      translation: 'она',
      image: 'assets/images/person/she.jpg',
      audioSrc: 'assets/music/person/she.mp3',
    },
    {
      word: 'it',
      translation: 'оно',
      image: 'assets/images/person/it.jpg',
      audioSrc: 'assets/music/person/it.mp3',
    },
    {
      word: 'parent',
      translation: 'родители',
      image: 'assets/images/person/parent.jpg',
      audioSrc: 'assets/music/person/parent.mp3',
    },
    {
      word: 'father',
      translation: 'отец',
      image: 'assets/images/person/father.jpg',
      audioSrc: 'assets/music/person/father.mp3',
    },
    {
      word: 'mother',
      translation: 'мать',
      image: 'assets/images/person/mother.jpg',
      audioSrc: 'assets/music/person/mother.mp3',
    },
    {
      word: 'son',
      translation: 'сын',
      image: 'assets/images/person/son.jpg',
      audioSrc: 'assets/music/person/son.mp3',
    },
    {
      word: 'daughter',
      translation: 'дочь',
      image: 'assets/images/person/daughter.jpg',
      audioSrc: 'assets/music/person/daughter.mp3',
    },
    {
      word: 'brother',
      translation: 'брат',
      image: 'assets/images/person/brother.jpg',
      audioSrc: 'assets/music/person/brother.mp3',
    },
    {
      word: 'sister',
      translation: 'сестра',
      image: 'assets/images/person/sister.jpg',
      audioSrc: 'assets/music/person/sister.mp3',
    },
    {
      word: 'grandfather',
      translation: 'дедушка',
      image: 'assets/images/person/grandfather.jpg',
      audioSrc: 'assets/music/person/grandfather.mp3',
    },
    {
      word: 'grandmother',
      translation: 'бабушка',
      image: 'assets/images/person/grandmother.jpg',
      audioSrc: 'assets/music/person/grandmother.mp3',
    },
    {
      word: 'uncle',
      translation: 'дядя',
      image: 'assets/images/person/uncle.jpg',
      audioSrc: 'assets/music/person/uncle.mp3',
    },
    {
      word: 'aunt',
      translation: 'тётя',
      image: 'assets/images/person/aunt.jpg',
      audioSrc: 'assets/music/person/aunt.mp3',
    },
    {
      word: 'cousin',
      translation: 'двоюродный брат/сестра',
      image: 'assets/images/person/cousin.jpg',
      audioSrc: 'assets/music/person/cousin.mp3',
    },
    {
      word: 'arm',
      translation: 'рука',
      image: 'assets/images/person/arm.jpg',
      audioSrc: 'assets/music/person/arm.mp3',
    },
    {
      word: 'back',
      translation: 'спина',
      image: 'assets/images/person/back.jpg',
      audioSrc: 'assets/music/person/back.mp3',
    },
    {
      word: 'beard',
      translation: 'борода',
      image: 'assets/images/person/beard.jpg',
      audioSrc: 'assets/music/person/beard.mp3',
    },
    {
      word: 'bone',
      translation: 'кость',
      image: 'assets/images/person/bone.jpg',
      audioSrc: 'assets/music/person/bone.mp3',
    },
    {
      word: 'cheek',
      translation: 'щека',
      image: 'assets/images/person/cheek.jpg',
      audioSrc: 'assets/music/person/cheek.mp3',
    },
    {
      word: 'chest',
      translation: 'грудь',
      image: 'assets/images/person/chest.jpg',
      audioSrc: 'assets/music/person/chest.mp3',
    },
    {
      word: 'chin',
      translation: 'подбородок',
      image: 'assets/images/person/chin.jpg',
      audioSrc: 'assets/music/person/chin.mp3',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: 'assets/images/person/ear.jpg',
      audioSrc: 'assets/music/person/ear.mp3',
    },
    {
      word: 'elbow',
      translation: 'локоть',
      image: 'assets/images/person/elbow.jpg',
      audioSrc: 'assets/music/person/elbow.mp3',
    },
    {
      word: 'eye',
      translation: 'глаз',
      image: 'assets/images/person/eye.jpg',
      audioSrc: 'assets/music/person/eye.mp3',
    },
    {
      word: 'eyebrow',
      translation: 'бровь',
      image: 'assets/images/person/eyebrow.jpg',
      audioSrc: 'assets/music/person/eyebrow.mp3',
    },
    {
      word: 'face',
      translation: 'лицо',
      image: 'assets/images/person/face.jpg',
      audioSrc: 'assets/music/person/face.mp3',
    },
    {
      word: 'finger',
      translation: 'палец',
      image: 'assets/images/person/finger.jpg',
      audioSrc: 'assets/music/person/finger.mp3',
    },
    {
      word: 'foot',
      translation: 'ступня',
      image: 'assets/images/person/foot.jpg',
      audioSrc: 'assets/music/person/foot.mp3',
    },
    {
      word: 'forehead',
      translation: 'лоб',
      image: 'assets/images/person/forehead.jpg',
      audioSrc: 'assets/music/person/forehead.mp3',
    },
    {
      word: 'hair',
      translation: 'волосы',
      image: 'assets/images/person/hair.jpg',
      audioSrc: 'assets/music/person/hair.mp3',
    },
    {
      word: 'hand',
      translation: 'кисти рук',
      image: 'assets/images/person/hand.jpg',
      audioSrc: 'assets/music/person/hand.mp3',
    },
    {
      word: 'head',
      translation: 'голова',
      image: 'assets/images/person/head.jpg',
      audioSrc: 'assets/music/person/head.mp3',
    },
    {
      word: 'heart',
      translation: 'сердце',
      image: 'assets/images/person/heart.jpg',
      audioSrc: 'assets/music/person/heart.mp3',
    },
    {
      word: 'heel',
      translation: 'пятка',
      image: 'assets/images/person/heel.jpg',
      audioSrc: 'assets/music/person/heel.mp3',
    },
    {
      word: 'knee',
      translation: 'колено',
      image: 'assets/images/person/knee.jpg',
      audioSrc: 'assets/music/person/knee.mp3',
    },
    {
      word: 'leg',
      translation: 'нога',
      image: 'assets/images/person/leg.jpg',
      audioSrc: 'assets/music/person/leg.mp3',
    },
    {
      word: 'lips',
      translation: 'губы',
      image: 'assets/images/person/lips.jpg',
      audioSrc: 'assets/music/person/lips.mp3',
    },
    {
      word: 'mouth',
      translation: 'рот',
      image: 'assets/images/person/mouth.jpg',
      audioSrc: 'assets/music/person/mouth.mp3',
    },
    {
      word: 'mustache',
      translation: 'усы',
      image: 'assets/images/person/mustache.jpg',
      audioSrc: 'assets/music/person/mustache.mp3',
    },
    {
      word: 'nail',
      translation: 'ноготь',
      image: 'assets/images/person/nail.jpg',
      audioSrc: 'assets/music/person/nail.mp3',
    },
    {
      word: 'neck',
      translation: 'шея',
      image: 'assets/images/person/neck.jpg',
      audioSrc: 'assets/music/person/neck.mp3',
    },
    {
      word: 'nose',
      translation: 'нос',
      image: 'assets/images/person/nose.jpg',
      audioSrc: 'assets/music/person/nose.mp3',
    },
    {
      word: 'organ',
      translation: 'орган',
      image: 'assets/images/person/organ.jpg',
      audioSrc: 'assets/music/person/organ.mp3',
    },
    {
      word: 'shoulder',
      translation: 'плечо',
      image: 'assets/images/person/shoulder.jpg',
      audioSrc: 'assets/music/person/shoulder.mp3',
    },
    {
      word: 'skin',
      translation: 'кожа',
      image: 'assets/images/person/skin.jpg',
      audioSrc: 'assets/music/person/skin.mp3',
    },
    {
      word: 'spine',
      translation: 'позвоночник',
      image: 'assets/images/person/spine.jpg',
      audioSrc: 'assets/music/person/spine.mp3',
    },
    {
      word: 'stomach',
      translation: 'живот, желудок',
      image: 'assets/images/person/stomach.jpg',
      audioSrc: 'assets/music/person/stomach.mp3',
    },
    {
      word: 'throat',
      translation: 'горло',
      image: 'assets/images/person/throat.jpg',
      audioSrc: 'assets/music/person/throat.mp3',
    },
    {
      word: 'toe',
      translation: 'палец на ноге',
      image: 'assets/images/person/toe.jpg',
      audioSrc: 'assets/music/person/toe.mp3',
    },
    {
      word: 'tongue',
      translation: 'язык',
      image: 'assets/images/person/tongue.jpg',
      audioSrc: 'assets/music/person/tongue.mp3',
    },
    {
      word: 'teeth',
      translation: 'зуб',
      image: 'assets/images/person/teeth.jpg',
      audioSrc: 'assets/music/person/teeth.mp3',
    },
    {
      word: 'blood',
      translation: 'кровь',
      image: 'assets/images/person/blood.jpg',
      audioSrc: 'assets/music/person/blood.mp3',
    },
    {
      word: 'bruise',
      translation: 'синяк',
      image: 'assets/images/person/bruise.jpg',
      audioSrc: 'assets/music/person/bruise.mp3',
    },
    {
      word: 'cough',
      translation: 'кашель',
      image: 'assets/images/person/cough.jpg',
      audioSrc: 'assets/music/person/cough.mp3',
    },
    {
      word: 'dizziness',
      translation: 'головокружение',
      image: 'assets/images/person/dizziness.jpg',
      audioSrc: 'assets/music/person/dizziness.mp3',
    },
    {
      word: 'fever',
      translation: 'жар',
      image: 'assets/images/person/fever.jpg',
      audioSrc: 'assets/music/person/fever.mp3',
    },
    {
      word: 'flu',
      translation: 'грипп',
      image: 'assets/images/person/flu.jpg',
      audioSrc: 'assets/music/person/flu.mp3',
    },
    {
      word: 'pain',
      translation: 'боль',
      image: 'assets/images/person/pain.jpg',
      audioSrc: 'assets/music/person/pain.mp3',
    },
    {
      word: 'spot',
      translation: 'пятно, точка',
      image: 'assets/images/person/spot.jpg',
      audioSrc: 'assets/music/person/spot.mp3',
    },
    {
      word: 'wound',
      translation: 'рана',
      image: 'assets/images/person/wound.jpg',
      audioSrc: 'assets/music/person/wound.mp3',
    },
    {
      word: 'sneeze',
      translation: 'чихать',
      image: 'assets/images/person/sneeze.jpg',
      audioSrc: 'assets/music/person/sneeze.mp3',
    },
    {
      word: 'hurt',
      translation: 'ранить, повреждать',
      image: 'assets/images/person/hurt.jpg',
      audioSrc: 'assets/music/person/hurt.mp3',
    },
    {
      word: 'fit',
      translation: 'в хорошей форме',
      image: 'assets/images/person/fit.jpg',
      audioSrc: 'assets/music/person/fit.mp3',
    },
    {
      word: 'healthy',
      translation: 'здоровый',
      image: 'assets/images/person/healthy.jpg',
      audioSrc: 'assets/music/person/healthy.mp3',
    },
    {
      word: 'swollen',
      translation: 'опухший',
      image: 'assets/images/person/swollen.jpg',
      audioSrc: 'assets/music/person/swollen.mp3',
    },
    {
      word: 'sick',
      translation: 'больной',
      image: 'assets/images/person/sick.jpg',
      audioSrc: 'assets/music/person/sick.mp3',
    },
    {
      word: 'fat',
      translation: 'толстый, жирный',
      image: 'assets/images/person/fat.jpg',
      audioSrc: 'assets/music/person/fat.mp3',
    },
    {
      word: 'dead',
      translation: 'мертвый',
      image: 'assets/images/person/dead.jpg',
      audioSrc: 'assets/music/person/dead.mp3',
    },
    {
      word: 'positive',
      translation: 'положительный',
      image: 'assets/images/person/positive.jpg',
      audioSrc: 'assets/music/person/positive.mp3',
    },
    {
      word: 'amazing',
      translation: 'удивительный',
      image: 'assets/images/person/amazing.jpg',
      audioSrc: 'assets/music/person/amazing.mp3',
    },
    {
      word: 'beautiful',
      translation: 'красивый',
      image: 'assets/images/person/beautiful.jpg',
      audioSrc: 'assets/music/person/beautiful.mp3',
    },
    {
      word: 'handsome',
      translation: 'красивый (о мужчине)',
      image: 'assets/images/person/handsome.jpg',
      audioSrc: 'assets/music/person/handsome.mp3',
    },
    {
      word: 'brave',
      translation: 'смелый',
      image: 'assets/images/person/brave.jpg',
      audioSrc: 'assets/music/person/brave.mp3',
    },
    {
      word: 'calm',
      translation: 'спокойный',
      image: 'assets/images/person/calm.jpg',
      audioSrc: 'assets/music/person/calm.mp3',
    },
    {
      word: 'careful',
      translation: 'осторожный',
      image: 'assets/images/person/careful.jpg',
      audioSrc: 'assets/music/person/careful.mp3',
    },
    {
      word: 'clever',
      translation: 'умный',
      image: 'assets/images/person/clever.jpg',
      audioSrc: 'assets/music/person/clever.mp3',
    },
    {
      word: 'curious',
      translation: 'любопытный',
      image: 'assets/images/person/curious.jpg',
      audioSrc: 'assets/music/person/curious.mp3',
    },
    {
      word: 'elegant',
      translation: 'элегантный',
      image: 'assets/images/person/elegant.jpg',
      audioSrc: 'assets/music/person/elegant.mp3',
    },
    {
      word: 'energetic',
      translation: 'энергичный',
      image: 'assets/images/person/energetic.jpg',
      audioSrc: 'assets/music/person/energetic.mp3',
    },
    {
      word: 'fair',
      translation: 'справедливый, честный',
      image: 'assets/images/person/fair.jpg',
      audioSrc: 'assets/music/person/fair.mp3',
    },
    {
      word: 'fine',
      translation: 'прекрасный, прекрасно',
      image: 'assets/images/person/fine.jpg',
      audioSrc: 'assets/music/person/fine.mp3',
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      image: 'assets/images/person/friendly.jpg',
      audioSrc: 'assets/music/person/friendly.mp3',
    },
    {
      word: 'good',
      translation: 'хороший, добрый',
      image: 'assets/images/person/good.jpg',
      audioSrc: 'assets/music/person/good.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'assets/images/person/happy.jpg',
      audioSrc: 'assets/music/person/happy.mp3',
    },
    {
      word: 'hard-working',
      translation: 'трудолюбивый',
      image: 'assets/images/person/hard-working.jpg',
      audioSrc: 'assets/music/person/hard-working.mp3',
    },
    {
      word: 'honest',
      translation: 'честный',
      image: 'assets/images/person/honest.jpg',
      audioSrc: 'assets/music/person/honest.mp3',
    },
    {
      word: 'kind',
      translation: 'добрый',
      image: 'assets/images/person/kind.jpg',
      audioSrc: 'assets/music/person/kind.mp3',
    },
    {
      word: 'lucky',
      translation: 'везучий, счастливый',
      image: 'assets/images/person/lucky.jpg',
      audioSrc: 'assets/music/person/lucky.mp3',
    },
    {
      word: 'nice',
      translation: 'милый, хороший, приятный',
      image: 'assets/images/person/nice.jpg',
      audioSrc: 'assets/music/person/nice.mp3',
    },
    {
      word: 'polite',
      translation: 'вежливый',
      image: 'assets/images/person/polite.jpg',
      audioSrc: 'assets/music/person/polite.mp3',
    },
    {
      word: 'talented',
      translation: 'талантливый',
      image: 'assets/images/person/talented.jpg',
      audioSrc: 'assets/music/person/talented.mp3',
    },
    {
      word: 'neutral',
      translation: 'нетральный',
      image: 'assets/images/person/neutral.jpg',
      audioSrc: 'assets/music/person/neutral.mp3',
    },
    {
      word: 'average',
      translation: 'средний',
      image: 'assets/images/person/average.jpg',
      audioSrc: 'assets/music/person/average.mp3',
    },
    {
      word: 'boring',
      translation: 'скучный',
      image: 'assets/images/person/boring.jpg',
      audioSrc: 'assets/music/person/boring.mp3',
    },
    {
      word: 'busy',
      translation: 'занятой',
      image: 'assets/images/person/busy.jpg',
      audioSrc: 'assets/music/person/busy.mp3',
    },
    {
      word: 'clumsy',
      translation: 'нуклюжий',
      image: 'assets/images/person/clumsy.jpg',
      audioSrc: 'assets/music/person/clumsy.mp3',
    },
    {
      word: 'dear',
      translation: 'дорогой',
      image: 'assets/images/person/dear.jpg',
      audioSrc: 'assets/music/person/dear.mp3',
    },
    {
      word: 'different',
      translation: 'другой, разный',
      image: 'assets/images/person/different.jpg',
      audioSrc: 'assets/music/person/different.mp3',
    },
    {
      word: 'difficult',
      translation: 'трудный, тяжелый',
      image: 'assets/images/person/difficult.jpg',
      audioSrc: 'assets/music/person/difficult.mp3',
    },
    {
      word: 'easy',
      translation: 'легкий, нетрудный',
      image: 'assets/images/person/easy.jpg',
      audioSrc: 'assets/music/person/easy.mp3',
    },
    {
      word: 'embarrassed',
      translation: 'смущенный',
      image: 'assets/images/person/embarrassed.jpg',
      audioSrc: 'assets/music/person/embarrassed.mp3',
    },
    {
      word: 'famous',
      translation: 'знаменитый',
      image: 'assets/images/person/famous.jpg',
      audioSrc: 'assets/music/person/famous.mp3',
    },
    {
      word: 'important',
      translation: 'важный',
      image: 'assets/images/person/important.jpg',
      audioSrc: 'assets/music/person/important.mp3',
    },
    {
      word: 'impossible',
      translation: 'невозможный',
      image: 'assets/images/person/impossible.jpg',
      audioSrc: 'assets/music/person/impossible.mp3',
    },
    {
      word: 'interesting',
      translation: 'интересный',
      image: 'assets/images/person/interesting.jpg',
      audioSrc: 'assets/music/person/interesting.mp3',
    },
    {
      word: 'real',
      translation: 'настоящий',
      image: 'assets/images/person/real.jpg',
      audioSrc: 'assets/music/person/real.mp3',
    },
    {
      word: 'rich',
      translation: 'богатый',
      image: 'assets/images/person/rich.jpg',
      audioSrc: 'assets/music/person/rich.mp3',
    },
    {
      word: 'new',
      translation: 'новый',
      image: 'assets/images/person/new.jpg',
      audioSrc: 'assets/music/person/new.mp3',
    },
    {
      word: 'modern',
      translation: 'современный',
      image: 'assets/images/person/modern.jpg',
      audioSrc: 'assets/music/person/modern.mp3',
    },
    {
      word: 'negative',
      translation: 'отрицательный',
      image: 'assets/images/person/negative.jpg',
      audioSrc: 'assets/music/person/negative.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'assets/images/person/angry.jpg',
      audioSrc: 'assets/music/person/angry.mp3',
    },
    {
      word: 'annoying',
      translation: 'раздражающий',
      image: 'assets/images/person/annoying.jpg',
      audioSrc: 'assets/music/person/annoying.mp3',
    },
    {
      word: 'awful',
      translation: 'ужасный, отвратительный',
      image: 'assets/images/person/awful.jpg',
      audioSrc: 'assets/music/person/awful.mp3',
    },
    {
      word: 'bad',
      translation: 'плохой',
      image: 'assets/images/person/bad.jpg',
      audioSrc: 'assets/music/person/bad.mp3',
    },
    {
      word: 'crazy',
      translation: 'безумный, сумасшедший',
      image: 'assets/images/person/crazy.jpg',
      audioSrc: 'assets/music/person/crazy.mp3',
    },
    {
      word: 'dangerous',
      translation: 'опасный',
      image: 'assets/images/person/dangerous.jpg',
      audioSrc: 'assets/music/person/dangerous.mp3',
    },
    {
      word: 'jealous',
      translation: 'ревнивый',
      image: 'assets/images/person/jealous.jpg',
      audioSrc: 'assets/music/person/jealous.mp3',
    },
    {
      word: 'lazy',
      translation: 'ленивый',
      image: 'assets/images/person/lazy.jpg',
      audioSrc: 'assets/music/person/lazy.mp3',
    },
    {
      word: 'nervous',
      translation: 'нервный',
      image: 'assets/images/person/nervous.jpg',
      audioSrc: 'assets/music/person/nervous.mp3',
    },
    {
      word: 'poor',
      translation: 'бедный, плохой (язык, знания)',
      image: 'assets/images/person/poor.jpg',
      audioSrc: 'assets/music/person/poor.mp3',
    },
    {
      word: 'rude',
      translation: 'грубый',
      image: 'assets/images/person/rude.jpg',
      audioSrc: 'assets/music/person/rude.mp3',
    },
    {
      word: 'accountant',
      translation: 'бухгалтер',
      image: 'assets/images/person/accountant.jpg',
      audioSrc: 'assets/music/person/accountant.mp3',
    },
    {
      word: 'actor',
      translation: 'актер',
      image: 'assets/images/person/actor.jpg',
      audioSrc: 'assets/music/person/actor.mp3',
    },
    {
      word: 'actress',
      translation: 'актриса',
      image: 'assets/images/person/actress.jpg',
      audioSrc: 'assets/music/person/actress.mp3',
    },
    {
      word: 'artist',
      translation: 'художник',
      image: 'assets/images/person/artist.jpg',
      audioSrc: 'assets/music/person/artist.mp3',
    },
    {
      word: 'boss',
      translation: 'босс',
      image: 'assets/images/person/boss.jpg',
      audioSrc: 'assets/music/person/boss.mp3',
    },
    {
      word: 'businessman',
      translation: 'бизнесмен',
      image: 'assets/images/person/businessman.jpg',
      audioSrc: 'assets/music/person/businessman.mp3',
    },
    {
      word: 'chief',
      translation: 'руководитель, главный',
      image: 'assets/images/person/chief.jpg',
      audioSrc: 'assets/music/person/chief.mp3',
    },
    {
      word: 'client',
      translation: 'клиент',
      image: 'assets/images/person/client.jpg',
      audioSrc: 'assets/music/person/client.mp3',
    },
    {
      word: 'colleague',
      translation: 'коллега',
      image: 'assets/images/person/colleague.jpg',
      audioSrc: 'assets/music/person/colleague.mp3',
    },
    {
      word: 'doctor',
      translation: 'врач',
      image: 'assets/images/person/doctor.jpg',
      audioSrc: 'assets/music/person/doctor.mp3',
    },
    {
      word: 'driver',
      translation: 'водитель',
      image: 'assets/images/person/driver.jpg',
      audioSrc: 'assets/music/person/driver.mp3',
    },
    {
      word: 'engineer',
      translation: 'инженер',
      image: 'assets/images/person/engineer.jpg',
      audioSrc: 'assets/music/person/engineer.mp3',
    },
    {
      word: 'journalist',
      translation: 'журналист',
      image: 'assets/images/person/journalist.jpg',
      audioSrc: 'assets/music/person/journalist.mp3',
    },
    {
      word: 'stewardess',
      translation: 'стюардесса',
      image: 'assets/images/person/stewardess.jpg',
      audioSrc: 'assets/music/person/stewardess.mp3',
    },
    {
      word: 'lawyer',
      translation: 'адвокат, юрист',
      image: 'assets/images/person/lawyer.jpg',
      audioSrc: 'assets/music/person/lawyer.mp3',
    },
    {
      word: 'lifeguard',
      translation: 'спасатель',
      image: 'assets/images/person/lifeguard.jpg',
      audioSrc: 'assets/music/person/lifeguard.mp3',
    },
    {
      word: 'mechanic',
      translation: 'механик',
      image: 'assets/images/person/mechanic.jpg',
      audioSrc: 'assets/music/person/mechanic.mp3',
    },
    {
      word: 'musician',
      translation: 'музыкант',
      image: 'assets/images/person/musician.jpg',
      audioSrc: 'assets/music/person/musician.mp3',
    },
    {
      word: 'nanny',
      translation: 'няня',
      image: 'assets/images/person/nanny.jpg',
      audioSrc: 'assets/music/person/nanny.mp3',
    },
    {
      word: 'nurse',
      translation: 'медсестра',
      image: 'assets/images/person/nurse.jpg',
      audioSrc: 'assets/music/person/nurse.mp3',
    },
    {
      word: 'pilot',
      translation: 'пилот',
      image: 'assets/images/person/pilot.jpg',
      audioSrc: 'assets/music/person/pilot.mp3',
    },
    {
      word: 'plumber',
      translation: 'сантехник',
      image: 'assets/images/person/plumber.jpg',
      audioSrc: 'assets/music/person/plumber.mp3',
    },
    {
      word: 'policeman',
      translation: 'полицейский',
      image: 'assets/images/person/policeman.jpg',
      audioSrc: 'assets/music/person/policeman.mp3',
    },
    {
      word: 'pupil',
      translation: 'школьник',
      image: 'assets/images/person/pupil.jpg',
      audioSrc: 'assets/music/person/pupil.mp3',
    },
    {
      word: 'seller',
      translation: 'продавец',
      image: 'assets/images/person/seller.jpg',
      audioSrc: 'assets/music/person/seller.mp3',
    },
    {
      word: 'student',
      translation: 'студент',
      image: 'assets/images/person/student.jpg',
      audioSrc: 'assets/music/person/student.mp3',
    },
    {
      word: 'teacher',
      translation: 'учитель',
      image: 'assets/images/person/teacher.jpg',
      audioSrc: 'assets/music/person/teacher.mp3',
    },
    {
      word: 'waiter',
      translation: 'официант',
      image: 'assets/images/person/waiter.jpg',
      audioSrc: 'assets/music/person/waiter.mp3',
    },
    {
      word: 'worker',
      translation: 'рабочий',
      image: 'assets/images/person/worker.jpg',
      audioSrc: 'assets/music/person/worker.mp3',
    },
    {
      word: 'area',
      translation: 'область, сфера, район',
      image: 'assets/images/person/area.jpg',
      audioSrc: 'assets/music/person/area.mp3',
    },
    {
      word: 'case',
      translation: 'дело',
      image: 'assets/images/person/case.jpg',
      audioSrc: 'assets/music/person/case.mp3',
    },
    {
      word: 'decision',
      translation: 'решение',
      image: 'assets/images/person/decision.jpg',
      audioSrc: 'assets/music/person/decision.mp3',
    },
    {
      word: 'duty',
      translation: 'обязанность',
      image: 'assets/images/person/duty.jpg',
      audioSrc: 'assets/music/person/duty.mp3',
    },
    {
      word: 'goal',
      translation: 'цель',
      image: 'assets/images/person/goal.jpg',
      audioSrc: 'assets/music/person/goal.mp3',
    },
    {
      word: 'list',
      translation: 'список',
      image: 'assets/images/person/list.jpg',
      audioSrc: 'assets/music/person/list.mp3',
    },
    {
      word: 'circumstance',
      translation: 'обстоятельство',
      image: 'assets/images/person/circumstance.jpg',
      audioSrc: 'assets/music/person/circumstance.mp3',
    },
    {
      word: 'opportunity',
      translation: 'возможность',
      image: 'assets/images/person/opportunity.jpg',
      audioSrc: 'assets/music/person/opportunity.mp3',
    },
    {
      word: 'problem',
      translation: 'проблема',
      image: 'assets/images/person/problem.jpg',
      audioSrc: 'assets/music/person/problem.mp3',
    },
    {
      word: 'permit',
      translation: 'разрешение',
      image: 'assets/images/person/permit.jpg',
      audioSrc: 'assets/music/person/permit.mp3',
    },
    {
      word: 'reason',
      translation: 'причина',
      image: 'assets/images/person/reason.jpg',
      audioSrc: 'assets/music/person/reason.mp3',
    },
    {
      word: 'result',
      translation: 'результат',
      image: 'assets/images/person/result.jpg',
      audioSrc: 'assets/music/person/result.mp3',
    },
    {
      word: 'success',
      translation: 'успех',
      image: 'assets/images/person/success.jpg',
      audioSrc: 'assets/music/person/success.mp3',
    },
    {
      word: 'task',
      translation: 'задача',
      image: 'assets/images/person/task.jpg',
      audioSrc: 'assets/music/person/task.mp3',
    },
    {
      word: 'clothes',
      translation: 'одежда',
      image: 'assets/images/person/clothes.jpg',
      audioSrc: 'assets/music/person/clothes.mp3',
    },
    {
      word: 'job',
      translation: 'работа',
      image: 'assets/images/person/job.jpg',
      audioSrc: 'assets/music/person/job.mp3',
    },
    {
      word: 'body',
      translation: 'тело',
      image: 'assets/images/person/body.jpg',
      audioSrc: 'assets/music/person/body.mp3',
    },
    {
      word: 'family',
      translation: 'семья',
      image: 'assets/images/person/family.jpg',
      audioSrc: 'assets/music/person/family.mp3',
    },
    {
      word: 'belt',
      translation: 'пояс, ремень',
      image: 'assets/images/person/belt.jpg',
      audioSrc: 'assets/music/person/belt.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/images/person/blouse.jpg',
      audioSrc: 'assets/music/person/blouse.mp3',
    },
    {
      word: 'boot',
      translation: 'сапог, ботинок',
      image: 'assets/images/person/boot.jpg',
      audioSrc: 'assets/music/person/boot.mp3',
    },
    {
      word: 'cap',
      translation: 'кепка',
      image: 'assets/images/person/cap.jpg',
      audioSrc: 'assets/music/person/cap.mp3',
    },
    {
      word: 'cardigan',
      translation: 'кардиган, кофта',
      image: 'assets/images/person/cardigan.jpg',
      audioSrc: 'assets/music/person/cardigan.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'assets/images/person/coat.jpg',
      audioSrc: 'assets/music/person/coat.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'assets/images/person/dress.jpg',
      audioSrc: 'assets/music/person/dress.mp3',
    },
    {
      word: 'glove',
      translation: 'перчатка',
      image: 'assets/images/person/glove.jpg',
      audioSrc: 'assets/music/person/glove.mp3',
    },
    {
      word: 'hat',
      translation: 'шляпа',
      image: 'assets/images/person/hat.jpg',
      audioSrc: 'assets/music/person/hat.mp3',
    },
    {
      word: 'hood',
      translation: 'капюшон',
      image: 'assets/images/person/hood.jpg',
      audioSrc: 'assets/music/person/hood.mp3',
    },
    {
      word: 'jacket',
      translation: 'жакет, пиджак, куртка',
      image: 'assets/images/person/jacket.jpg',
      audioSrc: 'assets/music/person/jacket.mp3',
    },
    {
      word: 'jeans',
      translation: 'джинсы',
      image: 'assets/images/person/jeans.jpg',
      audioSrc: 'assets/music/person/jeans.mp3',
    },
    {
      word: 'pyjamas',
      translation: 'пижама',
      image: 'assets/images/person/pyjamas.jpg',
      audioSrc: 'assets/music/person/pyjamas.mp3',
    },
    {
      word: 'scarf',
      translation: 'шарф',
      image: 'assets/images/person/scarf.jpg',
      audioSrc: 'assets/music/person/scarf.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'assets/images/person/shirt.jpg',
      audioSrc: 'assets/music/person/shirt.mp3',
    },
    {
      word: 'shoes',
      translation: 'обувь',
      image: 'assets/images/person/shoes.jpg',
      audioSrc: 'assets/music/person/shoes.mp3',
    },
    {
      word: 'shorts',
      translation: 'шорты',
      image: 'assets/images/person/shorts.jpg',
      audioSrc: 'assets/music/person/shorts.mp3',
    },
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'assets/images/person/skirt.jpg',
      audioSrc: 'assets/music/person/skirts.mp3',
    },
    {
      word: 'sock',
      translation: 'носок',
      image: 'assets/images/person/sock.jpg',
      audioSrc: 'assets/music/person/sock.mp3',
    },
    {
      word: 'suit',
      translation: 'костюм, идти к лицу',
      image: 'assets/images/person/suit.jpg',
      audioSrc: 'assets/music/person/suit.mp3',
    },
    {
      word: 'sweater',
      translation: 'свитер',
      image: 'assets/images/person/sweater.jpg',
      audioSrc: 'assets/music/person/sweater.mp3',
    },
    {
      word: 'tie',
      translation: 'галстук',
      image: 'assets/images/person/tie.jpg',
      audioSrc: 'assets/music/person/tie.mp3',
    },
    {
      word: 'tights',
      translation: 'колготы',
      image: 'assets/images/person/tights.jpg',
      audioSrc: 'assets/music/person/tights.mp3',
    },
    {
      word: 'trainers',
      translation: 'кроссовки',
      image: 'assets/images/person/trainers.jpg',
      audioSrc: 'assets/music/person/trainers.mp3',
    },
    {
      word: 'trousers',
      translation: 'штаны',
      image: 'assets/images/person/trousers.jpg',
      audioSrc: 'assets/music/person/trousers.mp3',
    },
    {
      word: 't-shirt',
      translation: 'футболка',
      image: 'assets/images/person/t-shirt.jpg',
      audioSrc: 'assets/music/person/t-shirt.mp3',
    },
    {
      word: 'underwear',
      translation: 'нижнее белье',
      image: 'assets/images/person/underwear.jpg',
      audioSrc: 'assets/music/person/underwear.mp3',
    },
    {
      word: 'bracelet',
      translation: 'браслет',
      image: 'assets/images/person/bracelet.jpg',
      audioSrc: 'assets/music/person/bracelet.mp3',
    },
    {
      word: 'earring',
      translation: 'сережка',
      image: 'assets/images/person/earring.jpg',
      audioSrc: 'assets/music/person/earring.mp3',
    },
    {
      word: 'glasses',
      translation: 'очки',
      image: 'assets/images/person/glasses.jpg',
      audioSrc: 'assets/music/person/glasses.mp3',
    },
    {
      word: 'necklace',
      translation: 'ожерелье',
      image: 'assets/images/person/necklace.jpg',
      audioSrc: 'assets/music/person/necklace.mp3',
    },
    {
      word: 'purse',
      translation: 'дамская сумка, кошелек',
      image: 'assets/images/person/purse.jpg',
      audioSrc: 'assets/music/person/purse.mp3',
    },
    {
      word: 'wallet',
      translation: 'бумажник',
      image: 'assets/images/person/wallet.jpg',
      audioSrc: 'assets/music/person/wallet.mp3',
    },
  ],
};

export default words;
